services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-cdn-proxy
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - app
